  <?php if(function_exists('osc_base_url')) { $base_url = osc_base_url(); } else { $base_url = 'http://www.elena.mb-themes.com/'; } ?>

  <img id="img-malaysia-map" src="<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png" border="0" width="400" height="200" orgWidth="400" orgHeight="200" usemap="#malaysia-map" alt="" oncontextmenu="return false" />
  <map name="malaysia-map" id="ImageMapsCom-malaysia-map" oncontextmenu="return false">
    <area  alt="" title="Perlis" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Perlis" shape="poly" coords="13,23,30,8,13,5" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/perlis.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Kedah" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Kedah" shape="poly" coords="17,38,29,39,29,52,38,43,47,23,51,12,34,8,16,25" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/kedah.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Penang" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Penang" shape="poly" coords="13,58,26,55,28,43,17,41,9,47" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/penang.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Perak" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Perak" shape="poly" coords="25,93,41,91,59,93,52,77,54,62,58,48,62,43,64,28,51,26,39,47,25,59,21,78" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/perak.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Kelantan" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Kelantan" shape="poly" coords="57,68,71,61,87,66,87,59,84,43,88,29,95,21,73,13,69,34,70,49,61,53" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/kelantan.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Terengannu" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Terengganu" shape="poly" coords="131,83,115,86,106,82,109,76,104,71,94,60,89,46,89,36,97,28,128,40" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/terengganu.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Pahang" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Pahang" shape="poly" coords="103,127,89,116,73,111,71,99,63,87,57,73,71,70,89,72,99,71,103,87,116,94,132,97,134,120,123,132" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/pahang.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Johor" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Johor" shape="poly" coords="88,161,95,138,97,128,107,136,125,137,137,131,156,167,139,186,110,186" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/johor.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Melaka" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Melaka" shape="poly" coords="78,156,90,145,90,139,73,139,69,149" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/melaka.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Negri Sembilan" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Negri+sembilan" shape="poly" coords="70,138,84,135,94,127,76,116,71,126" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/negri-sembilan.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Kuala Lumpur" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Kuala+lumpur" shape="poly" coords="58,113,63,108,59,106,56,109" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/kuala-lumpur.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Selangor" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Selangor" shape="poly" coords="28,114,30,95,42,98,54,99,64,98,65,108,71,115,67,123,63,141,39,134,57,116,63,115,62,107,56,107,55,106,54,112,54,117,39,133" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/selangor.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Sarawak" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Sarawak" shape="poly" coords="173,140,245,83,305,71,322,104,311,161,227,181,175,164" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/sarawak.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
    <area  alt="" title="Sabah" href="<?php echo $base_url; ?>index.php?page=search&sRegion=Sabah" shape="poly" coords="329,102,308,66,311,44,343,23,381,38,398,63,398,82,386,104" style="outline:none;" target="_self"  onmouseover="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/sabah.png';" onmouseout="if(document.images) document.getElementById('img-malaysia-map').src= '<?php echo $base_url; ?>oc-content/themes/elena/maps/my-map/all.png';"  />
  </map>
